name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test-oniguruma:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install build dependencies
        run: sudo apt-get install build-essential fakeroot git libsecret-1-dev
      - name: Build the package and run tests
        run: |
          curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
          chmod u+x build-package.sh
          ./build-package.sh
