name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test-oniguruma:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: UziTech/action-setup-atom@v1
        with:
          channel: ${{ matrix.channel }}
      - name: Atom version
        run: atom -v
      - name: APM version
        run: apm -v
      - name: Install dependencies
        run: apm install
      - name: Run tests
        run: atom --test spec
